
Sandbox_Cisco_XE: 
  hostname: devnetsandboxiosxe.cisco.com
  port: 22
  platform: ios
  username: admin
  password: C1sco12345


Sandbox_Cisco_XR: 
  hostname: sandbox-iosxr-1.cisco.com
  port: 22
  platform: ios
  username: admin
  password: C1sco12345

   
   